### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by rdewolff** [nylas/N1-Markdown-Composer#11]
Hello

After installing plugin manually, checking the pref to see it in the list and active and restarting Nylas N1, the plugin seems not to work. 

Looking at the logs, I found the following error :

```
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/error-logger.js:176 Streaming log data to /var/folders/zl/dwb01t4534nf9mffq5bzc2000000gn/T/Nylas-N1-1855.1857.log
index.js:15 Window load time: 767ms
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:222 Failed to load package named 'N1-Markdown-Composer'
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:223 Error: Cannot find module 'simplemde'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/module-cache.js:373:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:2:13)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:8:18)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:7:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:707:27)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:213:34
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:189:15)
    at Package.module.exports.Package.load (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:203:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:503:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:480:14)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:735:34
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:224 Cannot find module 'simplemde' Error: Cannot find module 'simplemde'(…)(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:224
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:301 Cannot find module 'simplemde'
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:302 Error: Cannot find module 'simplemde'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/module-cache.js:373:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:2:13)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:8:18)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:7:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:707:27)
    at Package.module.exports.Package.activateConfig (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:313:12)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:291:14)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:280:28
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:189:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:274:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:605:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:579:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:372:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:568:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:551:46)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:738:34
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:303 Failed to activate package named 'N1-Markdown-Composer' Error: Cannot find module 'simplemde'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/module-cache.js:373:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:2:13)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/markdown-editor.cjsx:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:8:18)
    at Object.<anonymous> (/Users/rdewolff/.nylas/packages/N1-Markdown-Composer/lib/main.cjsx:7:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .cjsx] (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:707:27)
    at Package.module.exports.Package.activateConfig (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:313:12)
    at Package.module.exports.Package.activateNow (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:291:14)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:280:28
    at Package.module.exports.Package.measure (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:189:15)
    at Package.module.exports.Package.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package.js:274:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:605:21)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:579:29
    at Config.module.exports.Config.transact (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/config.js:372:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:568:23)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Nylas N1.app/Contents/Resources/app.asar/src/package-manager.js:551:46)
    at /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:738:34
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:352  SCAN TABLE Thread-Counts for SELECT * FROM `Thread-Counts`
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:352  SCAN TABLE Category for SELECT `Category`.`data` FROM `Category`   
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:352  192msec: SELECT `Thread`.`data` FROM `Thread` INNER JOIN `Thread-Category` AS `M6` ON `M6`.`id` = `Thread`.`id` WHERE `M6`.`value` IN ('5229q6mep9mkj4e8xjshq2pjk','44b9wcfsp1esnkde2evkr0vf') AND `Thread`.`in_all_mail` = 1  ORDER BY `Thread`.`last_message_received_timestamp` DESC LIMIT 200 OFFSET 0
4/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/warning.js:48 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/flux/stores/database-store.js:352  143msec: SELECT `Thread`.`data` FROM `Thread` INNER JOIN `Thread-Contact` AS `M21` ON `M21`.`id` = `Thread`.`id` WHERE `M21`.`value` = 'rdewolff@gmail.com'  ORDER BY `Thread`.`last_message_received_timestamp` DESC LIMIT 100
10/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/warning.js:48 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

Any known issue? Any workaround?

**Comment by jstejada** [comment]
hey @rdewolff , this is due to installation issue #9. There's a workaround at the end of that thread, let me know if that works

**Comment by jstejada** [comment]
hi @rdewolff this should be fixed now
