### ISSUE TITLE
APM Error During Installation

### ISSUE THREAD

**Issue by al3xtjames** [nylas/N1-Markdown-Composer#3]
When attempting to install the plugin via Developer > Install a Package Manually, I received the following error:
![Image of Nylas N1 Error](http://i.imgur.com/hKF97gB.png)

I tried manually installing the simplemde package, but that didn't work either (resulted in the same error).

Anything else I should try?

**Comment by pachevalier** [comment]
+1 using Debian8 I've the same error.

**Comment by kukat** [comment]
+1

**Comment by nivv** [comment]
+1

**Comment by jacob-ogre** [comment]
+1 
OSX, N1 v0.3.45

**Comment by DarwinSenior** [comment]
+1

**Comment by bnsblue** [comment]
+1
OS X 10.11
N1 v0.3.45-3b5880e

**Comment by bnsblue** [comment]
I just got it worked lol. Here's what I did:
1) Install apm on my OSX (see [this](http://apple.stackexchange.com/questions/131348/how-to-make-command-apm-available-after-installing-atom))
2) `cd ~/.nylas/packages/N1-Markdown-Composer`
3) `apm install`
4) Done. 
This plugin now works like a charm!

**Comment by marclafountain** [comment]
I'm on the latest version of OS X and have this same issue.

I followed the steps that @bnsblue listed, Still getting the error.

I'm dying to use this plug-in, so I hope someone has a solution!

**Comment by nrutman** [comment]
I had the same problem and when I went into `~/.nylas/packages/N1-Markdown-Composer/` I saw an `npm-debug.log` file with the following contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Nylas N1.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Nylas N1.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/nathan/.nylas/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/nathan/.nylas/.apmrc',
1 verbose cli   'install',
1 verbose cli   '--target=0.36.7',
1 verbose cli   '--arch=x64' ]
2 info using npm@2.13.3
3 info using node@v0.10.40
4 verbose readDependencies loading dependencies from /Users/nathan/.nylas/packages/N1-Markdown-Composer-master/package.json
5 verbose install where, deps [ '/Users/nathan/.nylas/packages/N1-Markdown-Composer-master',
5 verbose install   [ 'simplemde', 'marked' ] ]
6 verbose install where, peers [ '/Users/nathan/.nylas/packages/N1-Markdown-Composer-master',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle /Users/nathan/.nylas/packages/N1-Markdown-Composer-master/package.json
8 info preinstall N1-Markdown-Composer@0.1.0
9 verbose readDependencies loading dependencies from /Users/nathan/.nylas/packages/N1-Markdown-Composer-master/package.json
10 silly cache add args [ 'simplemde@github:jstejada/simplemde-markdown-editor', null ]
11 verbose cache add spec simplemde@github:jstejada/simplemde-markdown-editor
12 silly cache add args [ 'marked@^0.3', null ]
13 verbose cache add spec marked@^0.3
14 silly cache add parsed spec { raw: 'marked@^0.3',
14 silly cache add   scope: null,
14 silly cache add   name: 'marked',
14 silly cache add   rawSpec: '^0.3',
14 silly cache add   spec: '>=0.3.0 <0.4.0',
14 silly cache add   type: 'range' }
15 silly addNamed marked@>=0.3.0 <0.4.0
16 verbose addNamed ">=0.3.0 <0.4.0" is a valid semver range for marked
17 silly addNameRange { name: 'marked', range: '>=0.3.0 <0.4.0', hasData: false }
18 silly mapToRegistry name marked
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/marked
22 verbose addNameRange registry:https://registry.npmjs.org/marked not in flight; fetching
23 silly cache add parsed spec { raw: 'simplemde@github:jstejada/simplemde-markdown-editor',
23 silly cache add   scope: null,
23 silly cache add   name: 'simplemde',
23 silly cache add   rawSpec: 'github:jstejada/simplemde-markdown-editor',
23 silly cache add   spec: 'github:jstejada/simplemde-markdown-editor',
23 silly cache add   type: 'hosted',
23 silly cache add   hosted:
23 silly cache add    { type: 'github',
23 silly cache add      ssh: 'git@github.com:jstejada/simplemde-markdown-editor.git',
23 silly cache add      sshUrl: 'git+ssh://git@github.com/jstejada/simplemde-markdown-editor.git',
23 silly cache add      httpsUrl: 'git+https://github.com/jstejada/simplemde-markdown-editor.git',
23 silly cache add      gitUrl: 'git://github.com/jstejada/simplemde-markdown-editor.git',
23 silly cache add      shortcut: 'github:jstejada/simplemde-markdown-editor',
23 silly cache add      directUrl: 'https://raw.githubusercontent.com/jstejada/simplemde-markdown-editor/master/package.json' } }
24 verbose addRemoteGit caching github:jstejada/simplemde-markdown-editor
25 verbose addRemoteGit jstejada/simplemde-markdown-editor is a repository hosted by github
26 silly tryGitProto attempting to clone git://github.com/jstejada/simplemde-markdown-editor.git
27 silly tryClone cloning jstejada/simplemde-markdown-editor via git://github.com/jstejada/simplemde-markdown-editor.git
28 verbose tryClone git-github-com-jstejada-simplemde-markdown-editor-git-924fd7fa not in flight; caching
29 verbose request uri https://registry.npmjs.org/marked
30 verbose request no auth needed
31 info attempt registry request try #1 at 07:53:13
32 verbose request id 5bb09a86bf86f788
33 http request GET https://registry.npmjs.org/marked
34 verbose makeDirectory /Users/nathan/.nylas/.apm/_git-remotes creation not in flight; initializing
35 silly makeDirectory /Users/nathan/.nylas/.apm/_git-remotes uid: 501 gid: 20
36 verbose git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror git://github.com/jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/git-github-com-jstejada-simplemde-markdown-editor-git-924fd7fa: undefined
36 verbose git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror git://github.com/jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/git-github-com-jstejada-simplemde-markdown-editor-git-924fd7fa: undefined
37 silly tryHTTPS attempting to clone git+https://github.com/jstejada/simplemde-markdown-editor.git
38 silly tryClone cloning jstejada/simplemde-markdown-editor via git+https://github.com/jstejada/simplemde-markdown-editor.git
39 verbose tryClone https-github-com-jstejada-simplemde-markdown-editor-git-0764f98e not in flight; caching
40 verbose git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror https://github.com/jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/https-github-com-jstejada-simplemde-markdown-editor-git-0764f98e: undefined
40 verbose git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror https://github.com/jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/https-github-com-jstejada-simplemde-markdown-editor-git-0764f98e: undefined
41 silly trySSH attempting to clone git@github.com:jstejada/simplemde-markdown-editor.git
42 silly tryClone cloning jstejada/simplemde-markdown-editor via git@github.com:jstejada/simplemde-markdown-editor.git
43 verbose tryClone git-github-com-jstejada-simplemde-markdown-editor-git-ebc23e86 not in flight; caching
44 error git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror git@github.com:jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/git-github-com-jstejada-simplemde-markdown-editor-git-ebc23e86: undefined
44 error git clone --template=/Users/nathan/.nylas/.apm/_git-remotes/_templates --mirror git@github.com:jstejada/simplemde-markdown-editor.git /Users/nathan/.nylas/.apm/_git-remotes/git-github-com-jstejada-simplemde-markdown-editor-git-ebc23e86: undefined
45 http 200 https://registry.npmjs.org/marked
46 silly get cb [ 200,
46 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
46 silly get     etag: '"E394UPD3DVRGP7UXH4MMECYQB"',
46 silly get     'content-type': 'application/json',
46 silly get     'cache-control': 'max-age=300',
46 silly get     'content-length': '47608',
46 silly get     'accept-ranges': 'bytes',
46 silly get     date: 'Fri, 26 Feb 2016 12:53:09 GMT',
46 silly get     via: '1.1 varnish',
46 silly get     age: '184',
46 silly get     connection: 'keep-alive',
46 silly get     'x-served-by': 'cache-atl6240-ATL',
46 silly get     'x-cache': 'HIT',
46 silly get     'x-cache-hits': '2',
46 silly get     'x-timer': 'S1456491189.944302,VS0,VE0',
46 silly get     vary: 'Accept' } ]
47 verbose get saving marked to /Users/nathan/.nylas/.apm/registry.npmjs.org/marked/.cache.json
48 silly addNameRange number 2 { name: 'marked', range: '>=0.3.0 <0.4.0', hasData: true }
49 silly addNameRange versions [ 'marked',
49 silly addNameRange   [ '0.0.1',
49 silly addNameRange     '0.0.2',
49 silly addNameRange     '0.0.3',
49 silly addNameRange     '0.0.4',
49 silly addNameRange     '0.0.5',
49 silly addNameRange     '0.0.6',
49 silly addNameRange     '0.0.7',
49 silly addNameRange     '0.0.8',
49 silly addNameRange     '0.0.9',
49 silly addNameRange     '0.1.0',
49 silly addNameRange     '0.1.1',
49 silly addNameRange     '0.1.2',
49 silly addNameRange     '0.1.3',
49 silly addNameRange     '0.1.4',
49 silly addNameRange     '0.1.5',
49 silly addNameRange     '0.1.6',
49 silly addNameRange     '0.1.7',
49 silly addNameRange     '0.1.8',
49 silly addNameRange     '0.1.9',
49 silly addNameRange     '0.2.0',
49 silly addNameRange     '0.2.1',
49 silly addNameRange     '0.2.2',
49 silly addNameRange     '0.2.2-1',
49 silly addNameRange     '0.2.3',
49 silly addNameRange     '0.2.4',
49 silly addNameRange     '0.2.4-1',
49 silly addNameRange     '0.2.5',
49 silly addNameRange     '0.2.6',
49 silly addNameRange     '0.2.7',
49 silly addNameRange     '0.2.8',
49 silly addNameRange     '0.2.9',
49 silly addNameRange     '0.2.10',
49 silly addNameRange     '0.3.0',
49 silly addNameRange     '0.3.1',
49 silly addNameRange     '0.3.2',
49 silly addNameRange     '0.3.3',
49 silly addNameRange     '0.3.4',
49 silly addNameRange     '0.3.5' ] ]
50 silly addNamed marked@0.3.5
51 verbose addNamed "0.3.5" is a plain semver version for marked
52 silly mapToRegistry name marked
53 silly mapToRegistry using default registry
54 silly mapToRegistry registry https://registry.npmjs.org/
55 silly mapToRegistry uri https://registry.npmjs.org/marked
56 verbose addRemoteTarball https://registry.npmjs.org/marked/-/marked-0.3.5.tgz not in flight; adding
57 verbose addRemoteTarball [ 'https://registry.npmjs.org/marked/-/marked-0.3.5.tgz',
57 verbose addRemoteTarball   '4113a15ac5d7bca158a5aae07224587b9fa15b94' ]
58 info retry fetch attempt 1 at 07:53:13
59 info attempt registry request try #1 at 07:53:13
60 http fetch GET https://registry.npmjs.org/marked/-/marked-0.3.5.tgz
61 http fetch 200 https://registry.npmjs.org/marked/-/marked-0.3.5.tgz
62 silly fetchAndShaCheck shasum 4113a15ac5d7bca158a5aae07224587b9fa15b94
63 verbose addTmpTarball /tmp/npm-52440-95d27f19/registry.npmjs.org/marked/-/marked-0.3.5.tgz not in flight; adding
64 verbose addTmpTarball already have metadata; skipping unpack for marked@0.3.5
65 silly cache afterAdd marked@0.3.5
66 verbose afterAdd /Users/nathan/.nylas/.apm/marked/0.3.5/package/package.json not in flight; writing
67 verbose afterAdd /Users/nathan/.nylas/.apm/marked/0.3.5/package/package.json written
68 verbose stack Error: not found: git
68 verbose stack     at F (/Applications/Nylas N1.app/Contents/Resources/app/apm/node_modules/npm/node_modules/which/which.js:72:28)
68 verbose stack     at E (/Applications/Nylas N1.app/Contents/Resources/app/apm/node_modules/npm/node_modules/which/which.js:75:29)
68 verbose stack     at /Applications/Nylas N1.app/Contents/Resources/app/apm/node_modules/npm/node_modules/which/which.js:83:16
68 verbose stack     at Object.oncomplete (fs.js:108:15)
69 verbose cwd /Users/nathan/.nylas/packages/N1-Markdown-Composer-master
70 error Darwin 15.3.0
71 error argv "/Applications/Nylas N1.app/Contents/Resources/app/apm/bin/node" "/Applications/Nylas N1.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/nathan/.nylas/.apm/.apmrc" "--userconfig" "/Users/nathan/.nylas/.apmrc" "install" "--target=0.36.7" "--arch=x64"
72 error node v0.10.40
73 error npm  v2.13.3
74 error code ENOGIT
75 error not found: git
76 error Failed using git.
76 error This is most likely not a problem with npm itself.
76 error Please check if you have git installed and in your PATH.
77 verbose exit [ 1, true ]
```

I do have git installed and it is on the path:

```
$ which git
/usr/local/bin/git
```

I hope that helps.

**Comment by nrutman** [comment]
I already have Atom installed, and manually installing the plugin packages seemed to work:

```
$ cd ~/.nylas/packages/N1-Markdown-Composer
$ apm install
Installing modules ✓
```

But now when I launch N1 (Version 0.4.9-575c091, OSX El Capitan) and open a new message, I just get a blank window:

![new_message_blank](https://cloud.githubusercontent.com/assets/165184/13353104/ed57d670-dc5f-11e5-9f82-c38f67b03d87.png)

**Comment by jstejada** [comment]
hi all, thanks for the details! I'm merging into duplicate #9. There's a workaround at the end of that issue. Let me know if that helps. Thanks!

**Comment by kpytka** [comment]
I used the workaround presented here but still I have a similar problem as @nrutman has. When the plugin is enabled, the message body is empty and can't be edited.
![screenshot 2016-04-18 19 10 22](https://cloud.githubusercontent.com/assets/5846329/14612834/993c5b16-0599-11e6-80fe-20ea931a4c54.png)

**Comment by jstejada** [comment]
thanks @kpytka, there seems to be an additional problem, I'll look into it soon

**Comment by jstejada** [comment]
hi @kpytka  and everyone else. any issues not related to installation should be fixed by now. I've also updated the readme with instructions to properly install the plugin
